//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KulGen.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KulGen.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        internal static string actionbar_options {
            get {
                return ResourceManager.GetString("actionbar_options", resourceCulture);
            }
        }
        
        internal static string actionbar_add_combatant {
            get {
                return ResourceManager.GetString("actionbar_add_combatant", resourceCulture);
            }
        }
        
        internal static string actionbar_edit_combatant {
            get {
                return ResourceManager.GetString("actionbar_edit_combatant", resourceCulture);
            }
        }
        
        internal static string actionbar_combat_tracker {
            get {
                return ResourceManager.GetString("actionbar_combat_tracker", resourceCulture);
            }
        }
        
        internal static string actionbar_help {
            get {
                return ResourceManager.GetString("actionbar_help", resourceCulture);
            }
        }
        
        internal static string init_title {
            get {
                return ResourceManager.GetString("init_title", resourceCulture);
            }
        }
        
        internal static string init_desc {
            get {
                return ResourceManager.GetString("init_desc", resourceCulture);
            }
        }
        
        internal static string init_asc {
            get {
                return ResourceManager.GetString("init_asc", resourceCulture);
            }
        }
        
        internal static string init_checkbox {
            get {
                return ResourceManager.GetString("init_checkbox", resourceCulture);
            }
        }
        
        internal static string multi_npc_title {
            get {
                return ResourceManager.GetString("multi_npc_title", resourceCulture);
            }
        }
        
        internal static string multi_npc_num {
            get {
                return ResourceManager.GetString("multi_npc_num", resourceCulture);
            }
        }
        
        internal static string multi_npc_alpha {
            get {
                return ResourceManager.GetString("multi_npc_alpha", resourceCulture);
            }
        }
        
        internal static string multi_npc_custom {
            get {
                return ResourceManager.GetString("multi_npc_custom", resourceCulture);
            }
        }
        
        internal static string multi_npc_custom_hint {
            get {
                return ResourceManager.GetString("multi_npc_custom_hint", resourceCulture);
            }
        }
        
        internal static string help_init_title {
            get {
                return ResourceManager.GetString("help_init_title", resourceCulture);
            }
        }
        
        internal static string help_init_standard {
            get {
                return ResourceManager.GetString("help_init_standard", resourceCulture);
            }
        }
        
        internal static string help_init_standard_desc {
            get {
                return ResourceManager.GetString("help_init_standard_desc", resourceCulture);
            }
        }
        
        internal static string help_init_greyhawk {
            get {
                return ResourceManager.GetString("help_init_greyhawk", resourceCulture);
            }
        }
        
        internal static string help_init_greyhawk_desc {
            get {
                return ResourceManager.GetString("help_init_greyhawk_desc", resourceCulture);
            }
        }
        
        internal static string help_init_narrative {
            get {
                return ResourceManager.GetString("help_init_narrative", resourceCulture);
            }
        }
        
        internal static string help_init_narrative_desc {
            get {
                return ResourceManager.GetString("help_init_narrative_desc", resourceCulture);
            }
        }
        
        internal static string help_click_here {
            get {
                return ResourceManager.GetString("help_click_here", resourceCulture);
            }
        }
        
        internal static string help_multi_title {
            get {
                return ResourceManager.GetString("help_multi_title", resourceCulture);
            }
        }
        
        internal static string help_multi_desc {
            get {
                return ResourceManager.GetString("help_multi_desc", resourceCulture);
            }
        }
        
        internal static string help_greyhawk_link {
            get {
                return ResourceManager.GetString("help_greyhawk_link", resourceCulture);
            }
        }
        
        internal static string help_narrative_link {
            get {
                return ResourceManager.GetString("help_narrative_link", resourceCulture);
            }
        }
    }
}
